global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'abdaouinessrine92@gmail.com'
  smtp_auth_username: 'abdaouinessrine92@gmail.com'
  smtp_auth_password: 'scmswinstpxmzhuj'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email-alert'

receivers:
- name: 'email-alert'
  email_configs:
  - to: 'mraihiamin@gmail.com'
    send_resolved: true

route:
  receiver: 'email-alert'
  group_by: ['job']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1m
  routes:
  - receiver: 'email-alert'
    match:
      severity: warning
