# Use a base image with Docker installed
FROM alpine

RUN apk update && apk add docker

# Copy the existing Dockerfile and application JAR into the container
COPY target/dashboard-0.0.1-SNAPSHOT.jar /app/dashboard.jar
COPY Dockerfile /app/

# Set the working directory inside the container
WORKDIR /app

# Expose the port on which the application will run
EXPOSE 8080

# Set the command to run when the container starts
CMD ["docker-compose", "up"]
