version: '3'
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=CRM_B2B_DASHBOARDV2
    ports:
      - "3308:3306"
  
  springboot-docker-container:
    build:
      context: .
      dockerfile: Dockerfile
    image: springboot-docker-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql-standalone
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: