version: '3.4'

services:
  dashboard:
    image: dashboard
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    platform: linux/x86_64
    restart: always
    image: "mysql:5.7"
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=CRM_B2B_DASHBOARD
      - MYSQL_USER: Nesrine
      - 
