# Use a base image with Docker and Python 3 installed
FROM alpine

RUN apk update && apk add docker

RUN apk add --no-cache python3

# Copy the existing Dockerfile, application JAR, and Python script into the container
COPY target/dashboard-0.0.1-SNAPSHOT.jar /app/dashboard.jar
COPY Dockerfile /app/
COPY test-py.py /app/

# Set the working directory inside the container
WORKDIR /app

# Expose the port on which the application will run
EXPOSE 8080

# Set the command to run when the container starts
CMD python3 script.py && docker-compose up